version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=password
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DB=richblogdbtest
      - PORT=80
    ports:
      - 8080:80
    networks:
      - app-network

  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
